import { IDiscoverMovie } from "types/api/discover";

export const FakeDiscoverMovie: IDiscoverMovie[] = [
  {
    adult: false,
    backdrop_path: "https://via.placeholder.com/220x330/000000",
    genre_ids: [0, 1],
    id: 1,
    original_language: "English",
    original_title: "Test Movie",
    overview: "Test Overview.",
    popularity: 100,
    poster_path: "https://via.placeholder.com/220x330/000000",
    release_date: "2012-01-01",
    title: "Test Movie",
    video: false,
    vote_average: 10,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "https://via.placeholder.com/220x330/000000",
    genre_ids: [0, 1],
    id: 1,
    original_language: "English",
    original_title: "Test Movie 2",
    overview: "Test Overview.",
    popularity: 100,
    poster_path: "https://via.placeholder.com/220x330/000000",
    release_date: "2012-01-01",
    title: "Test Movie 2",
    video: false,
    vote_average: 1,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "https://via.placeholder.com/220x330/000000",
    genre_ids: [0, 1],
    id: 1,
    original_language: "English",
    original_title:
      "Very Long Title Test Movie Test Movie Test Movie Test Movie Test Movie Test Movie Test Movie Test Movie Test Movie",
    overview:
      "Very Long Overview Test Overview Test Overview Test Overview Test Overview Test Overview Test Overview Test Overview Test Overview Test Overview.",
    popularity: 100,
    poster_path: "https://via.placeholder.com/220x330/000000",
    release_date: "2012-01-01",
    title:
      "Very Long Title Test Movie Test Movie Test Movie Test Movie Test Movie Test Movie Test Movie Test Movie Test Movie",
    video: false,
    vote_average: 5,
    vote_count: 10,
  },
];
