import { IMovieDetails } from "types/movie";

//https://api.themoviedb.org/3/movie/453395?api_key=API_KEY&language=en-US&append_to_response=external_ids,credits
export const FakeMovieData: IMovieDetails = {
  adult: false,
  backdrop_path: "/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
  belongs_to_collection: {
    id: 618529,
    name: "Doctor Strange Collection",
    poster_path: "/oa5uQOTY9Y4ERNrsDk7E0eC1E3h.jpg",
    backdrop_path: "/5ZuctJh5uX5L2dz1CjA7WsTJwZk.jpg",
  },
  budget: 200000001,
  genres: [
    {
      id: 14,
      name: "Fantasy",
    },
    {
      id: 28,
      name: "Action",
    },
    {
      id: 12,
      name: "Adventure",
    },
  ],
  homepage:
    "https://www.marvel.com/movies/doctor-strange-in-the-multiverse-of-madness",
  id: 453395,
  imdb_id: "tt9419884",
  original_language: "en",
  original_title: "Doctor Strange in the Multiverse of Madness",
  overview:
    "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
  popularity: 6343.173,
  poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
  production_companies: [
    {
      id: 420,
      logo_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
      name: "Marvel Studios",
      origin_country: "US",
    },
    {
      id: 176762,
      logo_path: null,
      name: "Kevin Feige Productions",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2022-05-04",
  revenue: 953200000,
  runtime: 126,
  spoken_languages: [
    {
      english_name: "Cantonese",
      iso_639_1: "cn",
      name: "广州话 / 廣州話",
    },
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
    {
      english_name: "Spanish",
      iso_639_1: "es",
      name: "Español",
    },
  ],
  status: "Released",
  tagline: "Enter a new dimension of Strange.",
  title: "Doctor Strange in the Multiverse of Madness",
  video: false,
  vote_average: 7.5,
  vote_count: 4131,
  external_ids: {
    imdb_id: "tt9419884",
    facebook_id: "DoctorStrangeOfficial",
    instagram_id: "doctorstrangeofficial",
    twitter_id: "DrStrange",
    id: 1,
  },
  credits: {
    cast: [
      {
        adult: false,
        gender: 2,
        id: 71580,
        known_for_department: "Acting",
        name: "Benedict Cumberbatch",
        original_name: "Benedict Cumberbatch",
        popularity: 59.549,
        profile_path: "/fBEucxECxGLKVHBznO0qHtCGiMO.jpg",
        cast_id: 2,
        character: "Dr. Stephen Strange / Sinister Strange / Defender Strange",
        credit_id: "58fa84bbc3a36879f40021db",
        order: 0,
      },
      {
        adult: false,
        gender: 1,
        id: 550843,
        known_for_department: "Acting",
        name: "Elizabeth Olsen",
        original_name: "Elizabeth Olsen",
        popularity: 45.499,
        profile_path: "/wIU675y4dofIDVuhaNWPizJNtep.jpg",
        cast_id: 10,
        character: "Wanda Maximoff / The Scarlet Witch",
        credit_id: "5d33bbc26a300b2f7ea6c7f4",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 5294,
        known_for_department: "Acting",
        name: "Chiwetel Ejiofor",
        original_name: "Chiwetel Ejiofor",
        popularity: 27.66,
        profile_path: "/kq5DDnqqofoRI0t6ddtRlsJnNPT.jpg",
        cast_id: 12,
        character: "Baron Karl Mordo",
        credit_id: "5d3b184d60c51d6c6a861ec2",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 30082,
        known_for_department: "Acting",
        name: "Benedict Wong",
        original_name: "Benedict Wong",
        popularity: 32.837,
        profile_path: "/ukmfsl59Isvn9odgzMWBidA3cmt.jpg",
        cast_id: 3,
        character: "Wong",
        credit_id: "58fab71dc3a36879be004e6f",
        order: 3,
      },
      {
        adult: false,
        gender: 1,
        id: 1912381,
        known_for_department: "Acting",
        name: "Xochitl Gomez",
        original_name: "Xochitl Gomez",
        popularity: 55.439,
        profile_path: "/y3aFdIpfT7GqVoVa523PqF9cJgO.jpg",
        cast_id: 29,
        character: "America Chavez",
        credit_id: "5f89c52be9da69003ae63fc8",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 1538879,
        known_for_department: "Acting",
        name: "Jett Klyne",
        original_name: "Jett Klyne",
        popularity: 19.489,
        profile_path: "/yrbY3ebII569deRr9NLD9kKV0HO.jpg",
        cast_id: 114,
        character: "Tommy Maximoff",
        credit_id: "624d9225bb2602009be9e965",
        order: 5,
      },
      {
        adult: false,
        gender: 2,
        id: 2047847,
        known_for_department: "Acting",
        name: "Julian Hilliard",
        original_name: "Julian Hilliard",
        popularity: 14.218,
        profile_path: "/umnRZFm9pQ9xB53PQwUPFOVul4j.jpg",
        cast_id: 113,
        character: "Billy Maximoff",
        credit_id: "624d92164cbe120065ba4861",
        order: 6,
      },
      {
        adult: false,
        gender: 1,
        id: 1851642,
        known_for_department: "Acting",
        name: "Sheila Atim",
        original_name: "Sheila Atim",
        popularity: 17.41,
        profile_path: "/vUNzuhGFT4SVeu5HqxKVU9eFCE.jpg",
        cast_id: 128,
        character: "Sara",
        credit_id: "627279bd7cffda73181755b9",
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 2211274,
        known_for_department: "Acting",
        name: "Adam Hugill",
        original_name: "Adam Hugill",
        popularity: 5.233,
        profile_path: "/o0XToJB2MrTtNm5n2g3UYxcMNrV.jpg",
        cast_id: 70,
        character: "Rintrah (voice)",
        credit_id: "61bf69eaa84ff700417e14df",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 72873,
        known_for_department: "Acting",
        name: "Michael Stuhlbarg",
        original_name: "Michael Stuhlbarg",
        popularity: 22.763,
        profile_path: "/seBk12MUK51aUoYX4OW1itfOpJ6.jpg",
        cast_id: 66,
        character: "Dr. Nicodemus 'Nic' West",
        credit_id: "61beabf5e24b930096d88961",
        order: 9,
      },
      {
        adult: false,
        gender: 1,
        id: 53714,
        known_for_department: "Acting",
        name: "Rachel McAdams",
        original_name: "Rachel McAdams",
        popularity: 26.862,
        profile_path: "/fxeMrZswIPIWhipvdRrHOVuPlQY.jpg",
        cast_id: 30,
        character: "Dr. Christine Palmer",
        credit_id: "5fd2552e1bf266003f04d9ce",
        order: 10,
      },
      {
        adult: false,
        gender: 1,
        id: 39459,
        known_for_department: "Acting",
        name: "Hayley Atwell",
        original_name: "Hayley Atwell",
        popularity: 54.415,
        profile_path: "/qpU7tIYUkKrVZXcEiULsvOawt48.jpg",
        cast_id: 121,
        character: "Peggy Carter / Captain Carter",
        credit_id: "626b04d7532acb0050762901",
        order: 11,
      },
      {
        adult: false,
        gender: 2,
        id: 56675,
        known_for_department: "Acting",
        name: "Anson Mount",
        original_name: "Anson Mount",
        popularity: 51.612,
        profile_path: "/qU6GGvUqwFMbfK2Bk7Gg7dK1KD6.jpg",
        cast_id: 125,
        character: "Blackagar Boltagon / Black Bolt",
        credit_id: "626ec2257cffda510800b09c",
        order: 12,
      },
      {
        adult: false,
        gender: 1,
        id: 1360281,
        known_for_department: "Acting",
        name: "Lashana Lynch",
        original_name: "Lashana Lynch",
        popularity: 20.6,
        profile_path: "/ypNxRag9uJ5nzPAN2um3amQK340.jpg",
        cast_id: 122,
        character: "Maria Rambeau / Captain Marvel",
        credit_id: "626c01be2ac499004fde352c",
        order: 13,
      },
      {
        adult: false,
        gender: 2,
        id: 17697,
        known_for_department: "Acting",
        name: "John Krasinski",
        original_name: "John Krasinski",
        popularity: 39.412,
        profile_path: "/qyOE30A2ctnn7QnPjXgxLAnBore.jpg",
        cast_id: 127,
        character: "Reed Richards / Mr. Fantastic",
        credit_id: "6272677d7cffda731817201a",
        order: 14,
      },
      {
        adult: false,
        gender: 2,
        id: 2387,
        known_for_department: "Acting",
        name: "Patrick Stewart",
        original_name: "Patrick Stewart",
        popularity: 31.107,
        profile_path: "/wEy5qSDT5jT3ZASc2hbwi59voPL.jpg",
        cast_id: 120,
        character: "Professor Charles Xavier / Professor X",
        credit_id: "6262a889c1ffbd10a231f8cf",
        order: 15,
      },
      {
        adult: false,
        gender: 1,
        id: 6885,
        known_for_department: "Acting",
        name: "Charlize Theron",
        original_name: "Charlize Theron",
        popularity: 42.076,
        profile_path: "/1HloWLLhL3iTrmDtMigiitLB9Qx.jpg",
        cast_id: 126,
        character: "Clea",
        credit_id: "6271f94e06f9840066b61d75",
        order: 16,
      },
      {
        adult: false,
        gender: 2,
        id: 11357,
        known_for_department: "Acting",
        name: "Bruce Campbell",
        original_name: "Bruce Campbell",
        popularity: 14.644,
        profile_path: "/p9335ljr7luOWsfwZSOlsIzFJKE.jpg",
        cast_id: 71,
        character: "Pizza Poppa",
        credit_id: "61c3d41bcae17c00519cbd01",
        order: 17,
      },
      {
        adult: false,
        gender: 2,
        id: 555249,
        known_for_department: "Acting",
        name: "Ross Marquand",
        original_name: "Ross Marquand",
        popularity: 12.75,
        profile_path: "/jIGiAslF6KWcdHMV2sf4bETv72C.jpg",
        cast_id: 129,
        character: "Ultron (voice)",
        credit_id: "627279ce7cffda7316c32bd5",
        order: 18,
      },
      {
        adult: false,
        gender: 2,
        id: 2366019,
        known_for_department: "Acting",
        name: "Andy Bale",
        original_name: "Andy Bale",
        popularity: 0.94,
        profile_path: "/jS51V2u8iNyu5gCDq5woAj36HA8.jpg",
        cast_id: 130,
        character: "Memory Lane Salesperson (voice)",
        credit_id: "627279dd162bc317aa346a89",
        order: 19,
      },
      {
        adult: false,
        gender: 0,
        id: 1363722,
        known_for_department: "Acting",
        name: "Ako Mitchell",
        original_name: "Ako Mitchell",
        popularity: 1.361,
        profile_path: "/5qxRjBZPP7RfRBDuzBf87TNkRia.jpg",
        cast_id: 131,
        character: "Charlie",
        credit_id: "627279e706f98400a945a379",
        order: 20,
      },
      {
        adult: false,
        gender: 1,
        id: 2476377,
        known_for_department: "Acting",
        name: "Momo Yeung",
        original_name: "Momo Yeung",
        popularity: 3.676,
        profile_path: "/7WypnP8AJtGtklaFqdbluGMlOm6.jpg",
        cast_id: 132,
        character: "Hong Kong Master",
        credit_id: "627279f16f53e158ec244e97",
        order: 21,
      },
      {
        adult: false,
        gender: 2,
        id: 2743994,
        known_for_department: "Acting",
        name: "Daniel Swain",
        original_name: "Daniel Swain",
        popularity: 0.6,
        profile_path: null,
        cast_id: 133,
        character: "London Master",
        credit_id: "62727a0129c626187bde5eff",
        order: 22,
      },
      {
        adult: false,
        gender: 0,
        id: 1703906,
        known_for_department: "Acting",
        name: "Topo Wresniwiro",
        original_name: "Topo Wresniwiro",
        popularity: 5.785,
        profile_path: "/xwpye9I6xOGOjE8JgizR7uylpfx.jpg",
        cast_id: 109,
        character: "Master Hamir",
        credit_id: "620b3b705b2f4700433d0a5a",
        order: 23,
      },
      {
        adult: false,
        gender: 1,
        id: 1480898,
        known_for_department: "Acting",
        name: "Eden Nathenson",
        original_name: "Eden Nathenson",
        popularity: 0.6,
        profile_path: null,
        cast_id: 134,
        character: "Ariann",
        credit_id: "62727a0ab6cff10067d25162",
        order: 24,
      },
      {
        adult: false,
        gender: 2,
        id: 3539133,
        known_for_department: "Acting",
        name: "Vinny Moli",
        original_name: "Vinny Moli",
        popularity: 0.6,
        profile_path: null,
        cast_id: 151,
        character: "Vinny",
        credit_id: "6275a6299979d2009b64c0d3",
        order: 25,
      },
      {
        adult: false,
        gender: 2,
        id: 2973171,
        known_for_department: "Acting",
        name: "Charlie Norton",
        original_name: "Charlie Norton",
        popularity: 0.6,
        profile_path: null,
        cast_id: 231,
        character: "The Weasel",
        credit_id: "6275b1b463a695004fd3479a",
        order: 26,
      },
      {
        adult: false,
        gender: 1,
        id: 3539134,
        known_for_department: "Acting",
        name: "Aliyah Camacho",
        original_name: "Aliyah Camacho",
        popularity: 0.6,
        profile_path: null,
        cast_id: 152,
        character: "Young America Chavez",
        credit_id: "6275a65377b1fb0050e9d992",
        order: 27,
      },
      {
        adult: false,
        gender: 1,
        id: 155868,
        known_for_department: "Acting",
        name: "Ruth Livier",
        original_name: "Ruth Livier",
        popularity: 6.571,
        profile_path: null,
        cast_id: 135,
        character: "Elena Chavez",
        credit_id: "62727a2d5800c40050db51c6",
        order: 28,
      },
      {
        adult: false,
        gender: 1,
        id: 3539135,
        known_for_department: "Acting",
        name: "Chess Lopez",
        original_name: "Chess Lopez",
        popularity: 0.6,
        profile_path: null,
        cast_id: 153,
        character: "Amalia Chavez",
        credit_id: "6275a673323eba0066ce6348",
        order: 29,
      },
      {
        adult: false,
        gender: 2,
        id: 1013950,
        known_for_department: "Acting",
        name: "David Tse",
        original_name: "David Tse",
        popularity: 1.558,
        profile_path: "/oJIcI5es35mHPBpyn9ohdog14hG.jpg",
        cast_id: 136,
        character: "Kamar-Taj Teacher",
        credit_id: "62727a7029c626187bde6045",
        order: 30,
      },
      {
        adult: false,
        gender: 0,
        id: 3539137,
        known_for_department: "Acting",
        name: "Yasmin Chadwick",
        original_name: "Yasmin Chadwick",
        popularity: 0.6,
        profile_path: null,
        cast_id: 154,
        character: "Rag Tag #1",
        credit_id: "6275a69d1b1f3c00671af0b8",
        order: 31,
      },
      {
        adult: false,
        gender: 2,
        id: 2744579,
        known_for_department: "Crew",
        name: "Anthony Knight",
        original_name: "Anthony Knight",
        popularity: 0.6,
        profile_path: null,
        cast_id: 155,
        character: "Rag Tag #2",
        credit_id: "6275a6aa724de100503c38a1",
        order: 32,
      },
      {
        adult: false,
        gender: 2,
        id: 3539139,
        known_for_department: "Acting",
        name: "Nuakai Aru",
        original_name: "Nuakai Aru",
        popularity: 0.6,
        profile_path: null,
        cast_id: 156,
        character: "Shield Bearer #1",
        credit_id: "6275a6de77b1fb009f493cd5",
        order: 33,
      },
      {
        adult: false,
        gender: 1,
        id: 1627840,
        known_for_department: "Acting",
        name: "Victoria Grove",
        original_name: "Victoria Grove",
        popularity: 1.139,
        profile_path: null,
        cast_id: 157,
        character: "Shield Bearer #2",
        credit_id: "6275a6ee713ea60066c2951a",
        order: 34,
      },
      {
        adult: false,
        gender: 2,
        id: 5925,
        known_for_department: "Acting",
        name: "Joshua Peace",
        original_name: "Joshua Peace",
        popularity: 5.379,
        profile_path: "/hzBO3jGfWLUwvcolw2zFxHlaRvO.jpg",
        cast_id: 137,
        character: "NY Passerby 616",
        credit_id: "62727a9306f98400a945a591",
        order: 35,
      },
      {
        adult: false,
        gender: 1,
        id: 2825529,
        known_for_department: "Crew",
        name: "Nina Jalava",
        original_name: "Nina Jalava",
        popularity: 0.6,
        profile_path: null,
        cast_id: 138,
        character: "Doctor Strange Fan",
        credit_id: "62727a9e5800c40050db535f",
        order: 36,
      },
      {
        adult: false,
        gender: 2,
        id: 2718957,
        known_for_department: "Acting",
        name: "Joshmaine Joseph",
        original_name: "Joshmaine Joseph",
        popularity: 0.6,
        profile_path: null,
        cast_id: 158,
        character: "Gargantos Fight Spectator #1",
        credit_id: "6275a73703bf840066c7124a",
        order: 37,
      },
      {
        adult: false,
        gender: 1,
        id: 3539144,
        known_for_department: "Acting",
        name: "Yenifer Molina",
        original_name: "Yenifer Molina",
        popularity: 0.6,
        profile_path: null,
        cast_id: 159,
        character: "Gargantos Fight Spectator #2",
        credit_id: "6275a746a5046e009ba07fd3",
        order: 38,
      },
      {
        adult: false,
        gender: 2,
        id: 3539276,
        known_for_department: "Acting",
        name: "Kevin Dalton",
        original_name: "Kevin Dalton",
        popularity: 0.6,
        profile_path: null,
        cast_id: 232,
        character: "Christine's Father",
        credit_id: "6275b28663a695004fd34af0",
        order: 40,
      },
      {
        adult: false,
        gender: 0,
        id: 3539146,
        known_for_department: "Acting",
        name: "Orphee Sidibe",
        original_name: "Orphee Sidibe",
        popularity: 0.6,
        profile_path: null,
        cast_id: 161,
        character: "Bio Room Staff #1",
        credit_id: "6275a77e03bf840050a2b948",
        order: 41,
      },
      {
        adult: false,
        gender: 2,
        id: 3539148,
        known_for_department: "Acting",
        name: "Gregory Fung",
        original_name: "Gregory Fung",
        popularity: 0.6,
        profile_path: null,
        cast_id: 162,
        character: "Bio Room Staff #2",
        credit_id: "6275a797713ea6009b88d469",
        order: 42,
      },
      {
        adult: false,
        gender: 1,
        id: 3080312,
        known_for_department: "Acting",
        name: "Cecilia Appiah",
        original_name: "Cecilia Appiah",
        popularity: 0.6,
        profile_path: "/qVFJGY2ALxwe7ku4QhpYHhgzDAl.jpg",
        cast_id: 163,
        character: "Waitress",
        credit_id: "6275a7b077b1fb009f493fd5",
        order: 43,
      },
      {
        adult: false,
        gender: 1,
        id: 3539149,
        known_for_department: "Acting",
        name: "Victoria Sterling",
        original_name: "Victoria Sterling",
        popularity: 0.6,
        profile_path: null,
        cast_id: 164,
        character: "Rag Tag Student",
        credit_id: "6275a7c7d236e60050c536fc",
        order: 44,
      },
      {
        adult: false,
        gender: 1,
        id: 3539152,
        known_for_department: "Acting",
        name: "Jordan Alexandra",
        original_name: "Jordan Alexandra",
        popularity: 0.6,
        profile_path: null,
        cast_id: 165,
        character: "Office Worker",
        credit_id: "6275a7e861bac40067b4b489",
        order: 45,
      },
      {
        adult: false,
        gender: 1,
        id: 3092061,
        known_for_department: "Acting",
        name: "Bobbie Little",
        original_name: "Bobbie Little",
        popularity: 0.6,
        profile_path: null,
        cast_id: 166,
        character: "Scared Woman #1",
        credit_id: "6275a7f59979d2005191f5d5",
        order: 46,
      },
      {
        adult: false,
        gender: 1,
        id: 3539154,
        known_for_department: "Acting",
        name: "Gabriella Cooper-Parsons",
        original_name: "Gabriella Cooper-Parsons",
        popularity: 0.6,
        profile_path: null,
        cast_id: 167,
        character: "Scared Woman #2",
        credit_id: "6275a80b61bac400513c9d89",
        order: 47,
      },
      {
        adult: false,
        gender: 2,
        id: 2804690,
        known_for_department: "Crew",
        name: "André Layne",
        original_name: "André Layne",
        popularity: 0.6,
        profile_path: null,
        cast_id: 168,
        character: "Sanctuary Guard",
        credit_id: "6275a81ef96a39009c950b8c",
        order: 48,
      },
      {
        adult: false,
        gender: 2,
        id: 2094567,
        known_for_department: "Writing",
        name: "Michael Waldron",
        original_name: "Michael Waldron",
        popularity: 6.555,
        profile_path: "/5d6wkYnJgkVAzThqnnwOLNDzACM.jpg",
        cast_id: 139,
        character: "Charlie's Best Man",
        credit_id: "62727ac65800c40050db53fa",
        order: 49,
      },
      {
        adult: false,
        gender: 1,
        id: 173428,
        known_for_department: "Acting",
        name: "Bridget Hoffman",
        original_name: "Bridget Hoffman",
        popularity: 4.939,
        profile_path: "/fmA0h836dBXd6Uhh3kqfmbG3X0O.jpg",
        cast_id: 169,
        character: "Soul of the Damned (voice)",
        credit_id: "6275a852e19de900a11b5bbe",
        order: 50,
      },
      {
        adult: false,
        gender: 2,
        id: 11641,
        known_for_department: "Acting",
        name: "Scott Spiegel",
        original_name: "Scott Spiegel",
        popularity: 6.77,
        profile_path: "/3dKveWiEUeQbAxC7o9AKkIUymPQ.jpg",
        cast_id: 170,
        character: "Soul of the Damned (voice)",
        credit_id: "6275a859a8023600500054dc",
        order: 51,
      },
      {
        adult: false,
        gender: 1,
        id: 173742,
        known_for_department: "Acting",
        name: "Jessica Pennington",
        original_name: "Jessica Pennington",
        popularity: 1.22,
        profile_path: null,
        cast_id: 171,
        character: "Soul of the Damned (voice)",
        credit_id: "6275a86295665800508d4f71",
        order: 52,
      },
      {
        adult: false,
        gender: 2,
        id: 80823,
        known_for_department: "Sound",
        name: "Andrew Morgado",
        original_name: "Andrew Morgado",
        popularity: 5.952,
        profile_path: "/rDkWTPcsFtw5MQCi1qxSXXZlXG2.jpg",
        cast_id: 172,
        character: "Soul of the Damned (voice)",
        credit_id: "6275a86ad236e60050c5390c",
        order: 53,
      },
      {
        adult: false,
        gender: 1,
        id: 86170,
        known_for_department: "Acting",
        name: "Audrey Wasilewski",
        original_name: "Audrey Wasilewski",
        popularity: 10.986,
        profile_path: "/4iUq8nA7hm2taO0vMMvvwtQvLr2.jpg",
        cast_id: 173,
        character: "Soul of the Damned (voice)",
        credit_id: "6275a87ee19de90051631955",
        order: 54,
      },
      {
        adult: false,
        gender: 2,
        id: 3173542,
        known_for_department: "Acting",
        name: "Christian Rummel",
        original_name: "Christian Rummel",
        popularity: 0.6,
        profile_path: null,
        cast_id: 174,
        character: "Soul of the Damned (voice)",
        credit_id: "6275a88567e0f70066d4a7dc",
        order: 55,
      },
      {
        adult: false,
        gender: 0,
        id: 2072553,
        known_for_department: "Production",
        name: "Richie Palmer",
        original_name: "Richie Palmer",
        popularity: 2.686,
        profile_path: null,
        cast_id: 175,
        character: "Soul of the Damned (voice)",
        credit_id: "6275a88dd236e60066e1f2c2",
        order: 56,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 531,
        known_for_department: "Sound",
        name: "Danny Elfman",
        original_name: "Danny Elfman",
        popularity: 3.381,
        profile_path: "/zFladKAPypbzp26Tfyeiy23vanH.jpg",
        credit_id: "602e756b0f3655003f275914",
        department: "Sound",
        job: "Original Music Composer",
      },
      {
        adult: false,
        gender: 2,
        id: 943,
        known_for_department: "Camera",
        name: "John Mathieson",
        original_name: "John Mathieson",
        popularity: 6.694,
        profile_path: "/AkWm67UMEWHhF3BDfH32HkRl5oM.jpg",
        credit_id: "603fe1304d679100244fc408",
        department: "Camera",
        job: "Director of Photography",
      },
      {
        adult: false,
        gender: 1,
        id: 7232,
        known_for_department: "Production",
        name: "Sarah Halley Finn",
        original_name: "Sarah Halley Finn",
        popularity: 9.03,
        profile_path: "/pI3OhmnHhXLEwuv0Vq6qJHivCJA.jpg",
        credit_id: "6030d94dfab3fa003efd0704",
        department: "Production",
        job: "Casting",
      },
      {
        adult: false,
        gender: 2,
        id: 7623,
        known_for_department: "Directing",
        name: "Sam Raimi",
        original_name: "Sam Raimi",
        popularity: 38.411,
        profile_path: "/rJJYL7N8OBL31K4anhZGv30NiL1.jpg",
        credit_id: "5e3b5fa3ac8e6b0011cab4cf",
        department: "Directing",
        job: "Director",
      },
      {
        adult: false,
        gender: 2,
        id: 7624,
        known_for_department: "Writing",
        name: "Stan Lee",
        original_name: "Stan Lee",
        popularity: 18.603,
        profile_path: "/kKeyWoFtTqOPsbmwylNHmuB3En9.jpg",
        credit_id: "619f1c0cbc2cb30042862359",
        department: "Writing",
        job: "Characters",
      },
      {
        adult: false,
        gender: 2,
        id: 7625,
        known_for_department: "Writing",
        name: "Steve Ditko",
        original_name: "Steve Ditko",
        popularity: 7.846,
        profile_path: "/x270c7XwNTnt8qhoZhW4xUzAqEX.jpg",
        credit_id: "619f1c21f90b1900614b3e32",
        department: "Writing",
        job: "Characters",
      },
      {
        adult: false,
        gender: 2,
        id: 7712,
        known_for_department: "Editing",
        name: "Bob Murawski",
        original_name: "Bob Murawski",
        popularity: 5.326,
        profile_path: null,
        credit_id: "615c63fbb1f68d006768ac4b",
        department: "Editing",
        job: "Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 10850,
        known_for_department: "Production",
        name: "Kevin Feige",
        original_name: "Kevin Feige",
        popularity: 9.494,
        profile_path: "/kCBqXZ5PT5udYGEj2wfTSFbLMvT.jpg",
        credit_id: "58fa848a925141643c0024c0",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 8166,
        known_for_department: "Sound",
        name: "Juan Peralta",
        original_name: "Juan Peralta",
        popularity: 2.748,
        profile_path: "/6ImDm04R5VmUAwBiXbvkJgJO480.jpg",
        credit_id: "6275a46e61bac40067b4a853",
        department: "Sound",
        job: "Sound Re-Recording Mixer",
      },
      {
        adult: false,
        gender: 0,
        id: 8850,
        known_for_department: "Production",
        name: "Helen Pollak",
        original_name: "Helen Pollak",
        popularity: 1.518,
        profile_path: null,
        credit_id: "6275a38ee786870051d6f3ef",
        department: "Production",
        job: "Unit Production Manager",
      },
      {
        adult: false,
        gender: 0,
        id: 8850,
        known_for_department: "Production",
        name: "Helen Pollak",
        original_name: "Helen Pollak",
        popularity: 1.518,
        profile_path: null,
        credit_id: "6275a383a5046e00505e427d",
        department: "Production",
        job: "Line Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 9818,
        known_for_department: "Art",
        name: "Julian Ashby",
        original_name: "Julian Ashby",
        popularity: 3.901,
        profile_path: null,
        credit_id: "61d22428e210230042212f99",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 2,
        id: 18866,
        known_for_department: "Writing",
        name: "Jack Kirby",
        original_name: "Jack Kirby",
        popularity: 5.697,
        profile_path: "/ihhR019gL1WrXdSQNJITAY6dont.jpg",
        credit_id: "6275acf8d236e60066e20356",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 18996,
        known_for_department: "Writing",
        name: "Joe Simon",
        original_name: "Joe Simon",
        popularity: 1.62,
        profile_path: null,
        credit_id: "6275ad91a885870068bcf430",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 24192,
        known_for_department: "Sound",
        name: "Dave Jordan",
        original_name: "Dave Jordan",
        popularity: 1.097,
        profile_path: null,
        credit_id: "624dbf3b629b2c0050556d38",
        department: "Sound",
        job: "Music Supervisor",
      },
      {
        adult: false,
        gender: 1,
        id: 25906,
        known_for_department: "Editing",
        name: "Tia Nolan",
        original_name: "Tia Nolan",
        popularity: 2.262,
        profile_path: null,
        credit_id: "623b2d42719aeb005dc491a5",
        department: "Editing",
        job: "Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 32349,
        known_for_department: "Art",
        name: "Charles Wood",
        original_name: "Charles Wood",
        popularity: 4.431,
        profile_path: "/lxhuwWMdbvuPzher5TSdGFsel1S.jpg",
        credit_id: "6032633f6e3deb003e0aa802",
        department: "Art",
        job: "Production Design",
      },
      {
        adult: false,
        gender: 2,
        id: 55499,
        known_for_department: "Directing",
        name: "Scott Derrickson",
        original_name: "Scott Derrickson",
        popularity: 5.699,
        profile_path: "/nOQkRTC6OPkUHebBfjIgtiZ0hvE.jpg",
        credit_id: "62099c6929733800f7afd9e6",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 57027,
        known_for_department: "Production",
        name: "Louis D'Esposito",
        original_name: "Louis D'Esposito",
        popularity: 9.177,
        profile_path: "/k9k3WWYdD3uDnrtwM60QirzG9cH.jpg",
        credit_id: "603264280a517c004194693f",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 113674,
        known_for_department: "Production",
        name: "Victoria Alonso",
        original_name: "Victoria Alonso",
        popularity: 6.931,
        profile_path: "/xF7Qe1tqgk9KtY8kThKHBWhMqxc.jpg",
        credit_id: "58fab827925141642f004ca1",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 35287,
        known_for_department: "Writing",
        name: "Gerry Conway",
        original_name: "Gerry Conway",
        popularity: 6.062,
        profile_path: "/6OkW13BXA30UR7g1v93gqTuOIeq.jpg",
        credit_id: "6275abc9713ea60066c2a6fd",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 128988,
        known_for_department: "Writing",
        name: "John Romita Jr.",
        original_name: "John Romita Jr.",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad7263a6950065a8947e",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 141359,
        known_for_department: "Writing",
        name: "Roy Thomas",
        original_name: "Roy Thomas",
        popularity: 3.601,
        profile_path: null,
        credit_id: "6275ada99450fe00a71b3a8a",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 207202,
        known_for_department: "Acting",
        name: "Jim Lee",
        original_name: "Jim Lee",
        popularity: 1.163,
        profile_path: "/cgCv75VFYq1LH8f0DzzBBrFwUJn.jpg",
        credit_id: "6275acff9979d2009b64da40",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 209343,
        known_for_department: "Writing",
        name: "Brian K. Vaughan",
        original_name: "Brian K. Vaughan",
        popularity: 1.847,
        profile_path: null,
        credit_id: "6275add1cf48a100abeacca7",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 220311,
        known_for_department: "Acting",
        name: "Matt Fraction",
        original_name: "Matt Fraction",
        popularity: 1.388,
        profile_path: null,
        credit_id: "6275ac7477b1fb0050e9eeba",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 934847,
        known_for_department: "Acting",
        name: "Chris Claremont",
        original_name: "Chris Claremont",
        popularity: 1.994,
        profile_path: "/wp5aESx8Hqa0aq4sN2m3L34FH3N.jpg",
        credit_id: "6275abba63a695004fd33374",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 983309,
        known_for_department: "Art",
        name: "Mike Stallion",
        original_name: "Mike Stallion",
        popularity: 2.716,
        profile_path: null,
        credit_id: "61d22487e10f460069621689",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 0,
        id: 1080216,
        known_for_department: "Acting",
        name: "Samuel Le",
        original_name: "Samuel Le",
        popularity: 1.646,
        profile_path: "/hluSVTYn19L6yn6bF96O9baQNrp.jpg",
        credit_id: "6275a9c303bf840050a2c0b4",
        department: "Crew",
        job: "Stunt Coordinator",
      },
      {
        adult: false,
        gender: 2,
        id: 1116441,
        known_for_department: "Writing",
        name: "Gene Colan",
        original_name: "Gene Colan",
        popularity: 2.835,
        profile_path: "/f3N37BElhbJwjEY2EI0JMdK9PTU.jpg",
        credit_id: "6275abc0cf48a100abeac4e1",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 1117747,
        known_for_department: "Production",
        name: "Mitchell Bell",
        original_name: "Mitchell Bell",
        popularity: 1.694,
        profile_path: null,
        credit_id: "6065e1d3daf57c002903d949",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1162716,
        known_for_department: "Directing",
        name: "John Bush",
        original_name: "John Bush",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6032637e6e3deb003e0aa838",
        department: "Art",
        job: "Set Decoration",
      },
      {
        adult: false,
        gender: 1,
        id: 1187669,
        known_for_department: "Art",
        name: "Sarah Stuart",
        original_name: "Sarah Stuart",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d224cc4f5801006772b866",
        department: "Art",
        job: "Assistant Art Director",
      },
      {
        adult: false,
        gender: 2,
        id: 1194953,
        known_for_department: "Crew",
        name: "John Byrne",
        original_name: "John Byrne",
        popularity: 3.087,
        profile_path: null,
        credit_id: "6275abab77b1fb009f494ece",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 1195199,
        known_for_department: "Writing",
        name: "John Romita, Sr.",
        original_name: "John Romita, Sr.",
        popularity: 1.388,
        profile_path: null,
        credit_id: "6275ad7c9450fe00a71b3a0f",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 1195200,
        known_for_department: "Writing",
        name: "David Michelinie",
        original_name: "David Michelinie",
        popularity: 2.528,
        profile_path: null,
        credit_id: "6275ad38a5046e00505e6403",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 1195563,
        known_for_department: "Writing",
        name: "Steven Grant",
        original_name: "Steven Grant",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275acbc724de1009ba5f6e8",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 1218986,
        known_for_department: "Writing",
        name: "Bryan Andrews",
        original_name: "Bryan Andrews",
        popularity: 6.235,
        profile_path: null,
        credit_id: "6275ae5ca5046e00505e6702",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 1222571,
        known_for_department: "Writing",
        name: "Mike Ploog",
        original_name: "Mike Ploog",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad6a323eba0066ce79eb",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 1237905,
        known_for_department: "Creator",
        name: "Joe Casey",
        original_name: "Joe Casey",
        popularity: 1.842,
        profile_path: null,
        credit_id: "6275abb361bac400513caa7b",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 1317647,
        known_for_department: "Costume & Make-Up",
        name: "Nicky Barron",
        original_name: "Nicky Barron",
        popularity: 1.22,
        profile_path: null,
        credit_id: "61d227a48c22c000998da229",
        department: "Costume & Make-Up",
        job: "Set Costumer",
      },
      {
        adult: false,
        gender: 0,
        id: 1323295,
        known_for_department: "Costume & Make-Up",
        name: "Graham Churchyard",
        original_name: "Graham Churchyard",
        popularity: 1.801,
        profile_path: null,
        credit_id: "624dc030c39266009c0bc304",
        department: "Costume & Make-Up",
        job: "Costume Design",
      },
      {
        adult: false,
        gender: 2,
        id: 1326451,
        known_for_department: "Art",
        name: "Thomas Brown",
        original_name: "Thomas Brown",
        popularity: 0.98,
        profile_path: null,
        credit_id: "61d224381c09fb0041e30536",
        department: "Art",
        job: "Supervising Art Director",
      },
      {
        adult: false,
        gender: 0,
        id: 1326460,
        known_for_department: "Art",
        name: "Mark Swain",
        original_name: "Mark Swain",
        popularity: 2.801,
        profile_path: null,
        credit_id: "61d22490aaec710066c67b42",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 1,
        id: 1327030,
        known_for_department: "Sound",
        name: "Lora Hirschberg",
        original_name: "Lora Hirschberg",
        popularity: 2.25,
        profile_path: "/gL4qn7THQn33BgSN2H4jRfuJJbU.jpg",
        credit_id: "6275a4659566580065b1bcb1",
        department: "Sound",
        job: "Sound Re-Recording Mixer",
      },
      {
        adult: false,
        gender: 0,
        id: 1360103,
        known_for_department: "Sound",
        name: "Addison Teague",
        original_name: "Addison Teague",
        popularity: 1.166,
        profile_path: null,
        credit_id: "61d22642f1b5710068962960",
        department: "Sound",
        job: "Supervising Sound Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 1372782,
        known_for_department: "Writing",
        name: "Steve Englehart",
        original_name: "Steve Englehart",
        popularity: 3.842,
        profile_path: null,
        credit_id: "6275ac5b9979d20067b6986d",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 1382000,
        known_for_department: "Writing",
        name: "Brian Michael Bendis",
        original_name: "Brian Michael Bendis",
        popularity: 1.822,
        profile_path: "/zYcyWooAjXFJCU7GVyzvHDqpPP0.jpg",
        credit_id: "6275ab8661bac40067b4c061",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 1401793,
        known_for_department: "Visual Effects",
        name: "Cyndi Ochs",
        original_name: "Cyndi Ochs",
        popularity: 1.179,
        profile_path: null,
        credit_id: "6275a328724de10066ac83ad",
        department: "Visual Effects",
        job: "Visual Effects Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1401968,
        known_for_department: "Visual Effects",
        name: "Janek Sirrs",
        original_name: "Janek Sirrs",
        popularity: 5.564,
        profile_path: null,
        credit_id: "6275a2f59450fe0051efea75",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1418408,
        known_for_department: "Costume & Make-Up",
        name: "Pamela Waggoner",
        original_name: "Pamela Waggoner",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d228114284ea001c9e39c7",
        department: "Costume & Make-Up",
        job: "Set Costumer",
      },
      {
        adult: false,
        gender: 1,
        id: 1439128,
        known_for_department: "Costume & Make-Up",
        name: "Charlotte Hayward",
        original_name: "Charlotte Hayward",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d2249f1b722c0019006702",
        department: "Costume & Make-Up",
        job: "Makeup Artist",
      },
      {
        adult: false,
        gender: 1,
        id: 1458578,
        known_for_department: "Sound",
        name: "Katy Wood",
        original_name: "Katy Wood",
        popularity: 1.62,
        profile_path: null,
        credit_id: "6275a414323eba00a761beb1",
        department: "Sound",
        job: "Supervising Sound Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 1472788,
        known_for_department: "Visual Effects",
        name: "Jamie Hallett",
        original_name: "Jamie Hallett",
        popularity: 2.843,
        profile_path: null,
        credit_id: "61d227249a3c4900417c8a32",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1512798,
        known_for_department: "Production",
        name: "Jamie Christopher",
        original_name: "Jamie Christopher",
        popularity: 6.691,
        profile_path: null,
        credit_id: "61f7688cac8e6b001c981471",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1559588,
        known_for_department: "Directing",
        name: "Dominic Fysh",
        original_name: "Dominic Fysh",
        popularity: 0.84,
        profile_path: null,
        credit_id: "6275a3c777b1fb009f49340a",
        department: "Directing",
        job: "First Assistant Director",
      },
      {
        adult: false,
        gender: 0,
        id: 1574034,
        known_for_department: "Art",
        name: "Oliver Carroll",
        original_name: "Oliver Carroll",
        popularity: 1.22,
        profile_path: null,
        credit_id: "6275aa1f77b1fb009f4949a2",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 2,
        id: 1585197,
        known_for_department: "Art",
        name: "Darrin Denlinger",
        original_name: "Darrin Denlinger",
        popularity: 1.4,
        profile_path: null,
        credit_id: "6065e22b0ff15a005878c585",
        department: "Art",
        job: "Storyboard Artist",
      },
      {
        adult: false,
        gender: 1,
        id: 1616065,
        known_for_department: "Crew",
        name: "Jo McLaren",
        original_name: "Jo McLaren",
        popularity: 0.6,
        profile_path: "/eQr8Zzsv4IuWlRmBnIuN36tWdCg.jpg",
        credit_id: "6275a9bb713ea60066c29f9f",
        department: "Crew",
        job: "Stunt Coordinator",
      },
      {
        adult: false,
        gender: 0,
        id: 1616066,
        known_for_department: "Art",
        name: "Aoife Warren",
        original_name: "Aoife Warren",
        popularity: 1.094,
        profile_path: null,
        credit_id: "61d225b3e10f4600926a608f",
        department: "Art",
        job: "Assistant Art Director",
      },
      {
        adult: false,
        gender: 1,
        id: 1621381,
        known_for_department: "Art",
        name: "Denise Ball",
        original_name: "Denise Ball",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d224bce2102300422130fc",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 2,
        id: 1643142,
        known_for_department: "Production",
        name: "Eric Hauserman Carroll",
        original_name: "Eric Hauserman Carroll",
        popularity: 1.427,
        profile_path: "/6rswcsUV6vrAgx0hM5pOpnhlaQl.jpg",
        credit_id: "61f767ec1092300095b6eead",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1701154,
        known_for_department: "Art",
        name: "Jeremy Simser",
        original_name: "Jeremy Simser",
        popularity: 0.75,
        profile_path: null,
        credit_id: "603263f85c3247003ede17e7",
        department: "Art",
        job: "Storyboard Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 1705237,
        known_for_department: "Visual Effects",
        name: "Joel Behrens",
        original_name: "Joel Behrens",
        popularity: 1.38,
        profile_path: null,
        credit_id: "61d226b77dfda60043b6837c",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1735572,
        known_for_department: "Crew",
        name: "Brycen Counts",
        original_name: "Brycen Counts",
        popularity: 1.073,
        profile_path: null,
        credit_id: "6275a9b367e0f70066d4ae7a",
        department: "Crew",
        job: "Stunt Coordinator",
      },
      {
        adult: false,
        gender: 0,
        id: 1739263,
        known_for_department: "Costume & Make-Up",
        name: "Chloe Reynolds",
        original_name: "Chloe Reynolds",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d227ff1b722c008befc652",
        department: "Costume & Make-Up",
        job: "Set Costumer",
      },
      {
        adult: false,
        gender: 2,
        id: 1753397,
        known_for_department: "Art",
        name: "Andy Park",
        original_name: "Andy Park",
        popularity: 0.6,
        profile_path: null,
        credit_id: "603263947f6c8d003d11c97d",
        department: "Art",
        job: "Conceptual Illustrator",
      },
      {
        adult: false,
        gender: 2,
        id: 1768857,
        known_for_department: "Writing",
        name: "Bill Mantlo",
        original_name: "Bill Mantlo",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad099450fe00a71b388a",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 1800431,
        known_for_department: "Art",
        name: "David Allcock",
        original_name: "David Allcock",
        popularity: 1.159,
        profile_path: null,
        credit_id: "6065e293a4af8f0057dfd3f8",
        department: "Art",
        job: "Storyboard Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 1804321,
        known_for_department: "Crew",
        name: "Roger Stern",
        original_name: "Roger Stern",
        popularity: 1.936,
        profile_path: null,
        credit_id: "6275ad9877b1fb0065870131",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 1829867,
        known_for_department: "Costume & Make-Up",
        name: "Tessa Phillips",
        original_name: "Tessa Phillips",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d227d88c22c0006cf45c42",
        department: "Costume & Make-Up",
        job: "Set Costumer",
      },
      {
        adult: false,
        gender: 0,
        id: 1915704,
        known_for_department: "Art",
        name: "Patrick Harris",
        original_name: "Patrick Harris",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d22472d8f44e008edc14be",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 0,
        id: 1992558,
        known_for_department: "Crew",
        name: "Russell Hopwood",
        original_name: "Russell Hopwood",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d2273a8c22c0001c2aa386",
        department: "Visual Effects",
        job: "Visual Effects",
      },
      {
        adult: false,
        gender: 0,
        id: 2000373,
        known_for_department: "Costume & Make-Up",
        name: "Birgitta Fredlund",
        original_name: "Birgitta Fredlund",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d227b6d19a33008e77c7c8",
        department: "Costume & Make-Up",
        job: "Costume Supervisor",
      },
      {
        adult: false,
        gender: 2,
        id: 2016325,
        known_for_department: "Sound",
        name: "Richard Gould",
        original_name: "Richard Gould",
        popularity: 0.6,
        profile_path: "/eSIi2hvbOo7NUDvtC4sbFG66250.jpg",
        credit_id: "61d225cd9a3c490066562874",
        department: "Sound",
        job: "Sound Effects Editor",
      },
      {
        adult: false,
        gender: 1,
        id: 2025837,
        known_for_department: "Art",
        name: "Tara Ilsley",
        original_name: "Tara Ilsley",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d225265541fa001aacef25",
        department: "Art",
        job: "Assistant Art Director",
      },
      {
        adult: false,
        gender: 0,
        id: 2025839,
        known_for_department: "Art",
        name: "Matt Hancock",
        original_name: "Matt Hancock",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d2250f22f5d70045908490",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 0,
        id: 2072553,
        known_for_department: "Production",
        name: "Richie Palmer",
        original_name: "Richie Palmer",
        popularity: 2.686,
        profile_path: null,
        credit_id: "624dbf864975600067569077",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 2094567,
        known_for_department: "Writing",
        name: "Michael Waldron",
        original_name: "Michael Waldron",
        popularity: 6.555,
        profile_path: "/5d6wkYnJgkVAzThqnnwOLNDzACM.jpg",
        credit_id: "5e3de21c98f1f1000f0eac07",
        department: "Writing",
        job: "Writer",
      },
      {
        adult: false,
        gender: 0,
        id: 2158594,
        known_for_department: "Art",
        name: "Richard Usher",
        original_name: "Richard Usher",
        popularity: 1.4,
        profile_path: null,
        credit_id: "61d225a8f1b5710043da59b5",
        department: "Art",
        job: "Standby Art Director",
      },
      {
        adult: false,
        gender: 0,
        id: 2161843,
        known_for_department: "Visual Effects",
        name: "Meagan Chancellor",
        original_name: "Meagan Chancellor",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d226d11684f700422c5745",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 2296692,
        known_for_department: "Writing",
        name: "Steve Epting",
        original_name: "Steve Epting",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ac64848eb9009cc43983",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 2387223,
        known_for_department: "Sound",
        name: "Paola Magrans",
        original_name: "Paola Magrans",
        popularity: 1.38,
        profile_path: null,
        credit_id: "61d226364284ea0065fa2130",
        department: "Sound",
        job: "Sound Effects Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 2395148,
        known_for_department: "Art",
        name: "Rupert Hancock",
        original_name: "Rupert Hancock",
        popularity: 0.98,
        profile_path: null,
        credit_id: "61d22519ec370c001ae4556e",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 0,
        id: 2395149,
        known_for_department: "Art",
        name: "Amy Herring",
        original_name: "Amy Herring",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275aac3323eba0066ce7220",
        department: "Art",
        job: "Art Department Assistant",
      },
      {
        adult: false,
        gender: 0,
        id: 2395151,
        known_for_department: "Art",
        name: "Austin Huntley",
        original_name: "Austin Huntley",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275aacd63a695004fd32f50",
        department: "Art",
        job: "Art Department Assistant",
      },
      {
        adult: false,
        gender: 0,
        id: 2395161,
        known_for_department: "Art",
        name: "Pete Thompson",
        original_name: "Pete Thompson",
        popularity: 0.6,
        profile_path: null,
        credit_id: "603263a57d5f4b004096accc",
        department: "Art",
        job: "Concept Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2399677,
        known_for_department: "Art",
        name: "Eric Yamamoto",
        original_name: "Eric Yamamoto",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6065e277daf57c0057a90593",
        department: "Art",
        job: "Storyboard Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 2420350,
        known_for_department: "Art",
        name: "Soren Bendt Aaboe Pedersen",
        original_name: "Soren Bendt Aaboe Pedersen",
        popularity: 1.388,
        profile_path: null,
        credit_id: "6065e264136545004023d94e",
        department: "Art",
        job: "Storyboard Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2615669,
        known_for_department: "Art",
        name: "Bob Cheshire",
        original_name: "Bob Cheshire",
        popularity: 0.6,
        profile_path: null,
        credit_id: "603263d596e30b00402452a2",
        department: "Art",
        job: "Concept Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2651706,
        known_for_department: "Production",
        name: "Karl Caffrey",
        original_name: "Karl Caffrey",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275a3ad61bac400a925d8f2",
        department: "Production",
        job: "Unit Production Manager",
      },
      {
        adult: false,
        gender: 2,
        id: 2652567,
        known_for_department: "Crew",
        name: "David Finch",
        original_name: "David Finch",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ac6ca5046e009ba0927e",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 2808013,
        known_for_department: "Visual Effects",
        name: "Reetu Aggarwal",
        original_name: "Reetu Aggarwal",
        popularity: 0.694,
        profile_path: null,
        credit_id: "619a00229603310062d471ac",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 1,
        id: 2825529,
        known_for_department: "Crew",
        name: "Nina Jalava",
        original_name: "Nina Jalava",
        popularity: 0.6,
        profile_path: null,
        credit_id: "62a2e660dc1cb44e3aa57224",
        department: "Crew",
        job: "Stand In",
      },
      {
        adult: false,
        gender: 0,
        id: 2833913,
        known_for_department: "Art",
        name: "Alex Smith",
        original_name: "Alex Smith",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275aa5ca8023600a6c8f66d",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 2,
        id: 2836393,
        known_for_department: "Visual Effects",
        name: "Alexander Ha",
        original_name: "Alexander Ha",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d226f77dfda60069077b1e",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2857595,
        known_for_department: "Art",
        name: "Jonathan Maris",
        original_name: "Jonathan Maris",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6065e24a9f5dfb0079764c8a",
        department: "Art",
        job: "Storyboard Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2880201,
        known_for_department: "Art",
        name: "James Flanagan",
        original_name: "James Flanagan",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d22500d19a33008e77c193",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 2,
        id: 2956585,
        known_for_department: "Crew",
        name: "Richard Howell",
        original_name: "Richard Howell",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275acf1f96a3900667ebf39",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 2985685,
        known_for_department: "Art",
        name: "Jakub Vykoukal",
        original_name: "Jakub Vykoukal",
        popularity: 0.6,
        profile_path: null,
        credit_id: "603263b47f6c8d003e112475",
        department: "Art",
        job: "Concept Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2985686,
        known_for_department: "Art",
        name: "Paul Chandler",
        original_name: "Paul Chandler",
        popularity: 0.6,
        profile_path: null,
        credit_id: "603263c71fb94f00428d73c2",
        department: "Art",
        job: "Concept Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2985688,
        known_for_department: "Art",
        name: "Thomas du Crest",
        original_name: "Thomas du Crest",
        popularity: 0.728,
        profile_path: null,
        credit_id: "603263e57f6c8d003c118a56",
        department: "Art",
        job: "Concept Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 3016142,
        known_for_department: "Crew",
        name: "Mark Gruenwald",
        original_name: "Mark Gruenwald",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275acde95665800508d62ed",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 3061780,
        known_for_department: "Visual Effects",
        name: "Jörundur Rafn Arnarson",
        original_name: "Jörundur Rafn Arnarson",
        popularity: 0.98,
        profile_path: null,
        credit_id: "61d226a58c22c00041381ed1",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 2,
        id: 3119300,
        known_for_department: "Crew",
        name: "Kieron Gillen",
        original_name: "Kieron Gillen",
        popularity: 0.625,
        profile_path: null,
        credit_id: "6275ac7b724de100503c4fa5",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 3119306,
        known_for_department: "Crew",
        name: "Jamie McKelvie",
        original_name: "Jamie McKelvie",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad20a5046e009ba09552",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 3169987,
        known_for_department: "Visual Effects",
        name: "Daniel Hazeltine",
        original_name: "Daniel Hazeltine",
        popularity: 3.65,
        profile_path: null,
        credit_id: "61d2272ee194b000413c3d9e",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 3202369,
        known_for_department: "Crew",
        name: "Jonathan Hickman",
        original_name: "Jonathan Hickman",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ace7713ea6009b88e773",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3218705,
        known_for_department: "Crew",
        name: "Winslow Mortimer",
        original_name: "Winslow Mortimer",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad61a885870068bcf30d",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 1,
        id: 3218707,
        known_for_department: "Crew",
        name: "Jean Thomas",
        original_name: "Jean Thomas",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ada103bf8400a28cadbb",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3237677,
        known_for_department: "Visual Effects",
        name: "Daniel Edery",
        original_name: "Daniel Edery",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61442a0794d8a80067e317dc",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 3258648,
        known_for_department: "Costume & Make-Up",
        name: "Sally Crawshaw",
        original_name: "Sally Crawshaw",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d224a95541fa008b130657",
        department: "Costume & Make-Up",
        job: "Makeup Artist",
      },
      {
        adult: false,
        gender: 1,
        id: 3345680,
        known_for_department: "Art",
        name: "Gina Cimmelli",
        original_name: "Gina Cimmelli",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d224e71b722c00412b837e",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 2,
        id: 3447161,
        known_for_department: "Crew",
        name: "Kent Gordon",
        original_name: "Kent Gordon",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ae769979d2009b64dfed",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 3486135,
        known_for_department: "Crew",
        name: "Chris Warner",
        original_name: "Chris Warner",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275addca885870068bcf501",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 1,
        id: 3539190,
        known_for_department: "Art",
        name: "Sarah Greenslade",
        original_name: "Sarah Greenslade",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275aab2848eb900505a5fba",
        department: "Art",
        job: "Art Department Coordinator",
      },
      {
        adult: false,
        gender: 1,
        id: 3539196,
        known_for_department: "Art",
        name: "Megan Clough-Ambridge",
        original_name: "Megan Clough-Ambridge",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ab00724de10066ac9d4b",
        department: "Art",
        job: "Art Department Assistant",
      },
      {
        adult: false,
        gender: 2,
        id: 3539198,
        known_for_department: "Crew",
        name: "Peter Alberti",
        original_name: "Peter Alberti",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ab3463a695004fd33107",
        department: "Crew",
        job: "Stand In",
      },
      {
        adult: false,
        gender: 0,
        id: 3539201,
        known_for_department: "Crew",
        name: "Becky Tun Pe",
        original_name: "Becky Tun Pe",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ab43848eb900505a618a",
        department: "Crew",
        job: "Stand In",
      },
      {
        adult: false,
        gender: 2,
        id: 3539207,
        known_for_department: "Crew",
        name: "Frank Brunner",
        original_name: "Frank Brunner",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ab9f9566580065b1d26a",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3539216,
        known_for_department: "Crew",
        name: "Alan Davis",
        original_name: "Alan Davis",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ac3967e0f700519abbdd",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3539218,
        known_for_department: "Crew",
        name: "Terry Dodson",
        original_name: "Terry Dodson",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ac45a885870068bcee79",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3539219,
        known_for_department: "Crew",
        name: "Nick Dragotta",
        original_name: "Nick Dragotta",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ac50a5046e00505e617f",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3539223,
        known_for_department: "Crew",
        name: "Peter B. Gillis",
        original_name: "Peter B. Gillis",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ac911b1f3c0051e519a5",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3539228,
        known_for_department: "Crew",
        name: "Marcos Martín",
        original_name: "Marcos Martín",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad19f96a39009c951db8",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3539229,
        known_for_department: "Crew",
        name: "Steve McNiven",
        original_name: "Steve McNiven",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad2e72d8550068da7e44",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 0,
        id: 3539233,
        known_for_department: "Crew",
        name: "Yong Montaño",
        original_name: "Yong Montaño",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad59e19de9005163297d",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 1,
        id: 3539238,
        known_for_department: "Crew",
        name: "Marie Severin",
        original_name: "Marie Severin",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ad86a885870068bcf3ea",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3539241,
        known_for_department: "Crew",
        name: "Dave Thorpe",
        original_name: "Dave Thorpe",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275adc663a6950065a895ae",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 1,
        id: 3539245,
        known_for_department: "Crew",
        name: "JC Lee",
        original_name: "JC Lee",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6275ae53cf48a100abeaceb4",
        department: "Crew",
        job: "Thanks",
      },
      {
        adult: false,
        gender: 2,
        id: 3611429,
        known_for_department: "Crew",
        name: "Al Milgrom",
        original_name: "Al Milgrom",
        popularity: 0.84,
        profile_path: null,
        credit_id: "62c2c0c7544c41004cb787d0",
        department: "Crew",
        job: "Thanks",
      },
    ],
  },
};
